# Generated by Django 6.0.2 on 2026-02-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarionegocio_rol'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarionegocio'),
        ),
    ]
