# Generated by Django 6.0.2 on 2026-02-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarionegocio',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('ALMACEN', 'Almacén'), ('AlMACEN-ADMIN', 'Almacén-Admin')], max_length=20),
        ),
    ]
