# Generated by Django 6.0.2 on 2026-02-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=-1),
        ),
    ]
